# Generated by Django 4.2.7 on 2023-11-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geolocation',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
