# Generated by Django 4.2.7 on 2023-11-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0003_alter_geolocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='latitude',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='longitude',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
