# Generated by Django 4.2.7 on 2023-11-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0004_alter_geolocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
